### ISSUE TITLE
Add guillotine fields for all form fields in addition to single `text`

### ISSUE THREAD

**Issue by pmi** [enonic/app-robots-txt#46]
We have the following form:

![image](https://github.com/enonic/app-robots-txt/assets/754221/ea491db5-4d7a-4015-86c1-d43b61b8216f)

But the fact that everything is combined into single `text` field in guillotine makes it necessary to parse it back in Next.js.

Because Next.js needs following fields:
- rules: Rule | Rule[]
- sitemap?: string | string[]
- host?

where `Rule` is:
```
{
    userAgent?: string | string[];
    allow?: string | string[];
    disallow?: string | string[];
    crawlDelay?: number;
}
```

So, since we have them anyway, why can't we just expose them ?

**Comment by rymsha** [comment]
There are two ways to expose robots.txt in Next.js.

First one - when you already have the text.
via route https://nextjs.org/docs/pages/building-your-application/routing/api 
and rewrites https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites 

Second one  - is using Robots generation. 
This method did not exist until recently. https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots 
Benefits of using it are not that clear then the application itself can already build the text. (maybe Next.js can aggressively cache it?)
But since Next.js now provides it, we may consider adding the fields
